/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/girl-animation.glb -o src/components/AnimatedGirl.jsx -r public 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AnimatedGirl({isMoving, isJumping, isRunning, props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/girl-animation.glb')
  const { actions } = useAnimations(animations, group)
  const [animation, setAnimation] = useState("idle");

  useEffect(() => {
    const action = actions[animation];
    action.reset().fadeIn(0.32).play();
    return () => action?.fadeOut(0.32);
  }, [animation, actions]);

  useEffect(() => {
    if (isMoving) {
      if (isRunning) {
        setAnimation('run');
      } else {
        setAnimation('walk');
      }
    } else if (isJumping) {
      setAnimation('jump');
    } else {
      setAnimation('idle');
    }
  }, [isMoving, isJumping, isRunning]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="idle" rotation={[Math.PI / 2, 0, 0]} scale={0.01} position={[0,-1.1,0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch03" geometry={nodes.Ch03.geometry} material={materials.Ch03_Body} skeleton={nodes.Ch03.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/girl-animation.glb')
