/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Phongtruyenthong.glb -o src/components/PTTRoom.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three"

export function PTTRoom(props) {

  const { nodes, materials } = useGLTF('/models/Phongtruyenthong.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.017, 0, 0.383]} rotation={[-Math.PI / 2, 0, 0]} scale={0.018}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Mat_1.001']} position={[0, 0, 1.13]} />
      </group>
      <group position={[-10.554, 4.189, 5.644]} rotation={[-Math.PI / 2, 0, 0]} scale={0.446}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 504.656, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[85.224, 347.306, 65.686]}>
            <mesh geometry={nodes.Plane_Black_0001.geometry} material={materials.Black} />
            <mesh geometry={nodes.Plane_White_0001.geometry} material={materials.White} />
          </group>
          <mesh geometry={nodes.Plane001_Gray_0001.geometry} material={materials.Gray} position={[-0.024, 504.656, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[85.224, 347.306, 96.52]} />
          <mesh geometry={nodes.Plane002_White_0001.geometry} material={materials.White} position={[85.914, 429.029, 0]} rotation={[-Math.PI / 2, 0.38, 0]} scale={[85.224, 347.306, 65.686]} />
          <mesh geometry={nodes.Plane003_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[46.458, 461.25, -1.901]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane004_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[46.458, 461.25, 271.326]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane005_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[46.458, 461.25, -269.031]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane006_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, -41.28]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane007_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, 39.563]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane008_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, 121.084]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane009_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, 204.062]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane010_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, -126.167]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane011_Light_Gray_0001.geometry} material={materials.Light_Gray} position={[35.161, 445.017, -210.961]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane012_Black_0001.geometry} material={materials.Black} position={[104.789, 472.452, -327.121]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[7.978, 11.987, 29.106]} />
          <mesh geometry={nodes.Plane013_Black_0001.geometry} material={materials.Black} position={[105.845, 476.109, -271.105]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[2.635, 10.971, 9.614]} />
          <mesh geometry={nodes.Plane014_Black_0001.geometry} material={materials.Black} position={[103.458, 468.024, -271.105]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[2.635, 10.971, 9.614]} />
          <mesh geometry={nodes.Plane015_Green_0001.geometry} material={materials.Green} position={[105.845, 476.109, -245.105]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[1.808, 5.31, 8.918]} />
          <mesh geometry={nodes.Plane016_Red_0001.geometry} material={materials.material} position={[103.669, 468.189, -245.105]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[1.808, 5.31, 8.918]} />
          <mesh geometry={nodes.Plane017_Black_0001.geometry} material={materials.Black} position={[104.789, 472.452, -221.508]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[4.437, 4.883, 16.188]} />
          <mesh geometry={nodes.Text_Yellow_0001.geometry} material={materials.Yellow} position={[104.965, 471.902, -326.39]} rotation={[Math.PI / 2, 1.277, -Math.PI / 2]} scale={16.971} />
        </group>
      </group>
      <group position={[-10.554, 4.442, -4.086]} rotation={[-Math.PI / 2, 0, 0]} scale={0.446}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 447.864, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[85.224, 347.306, 65.686]}>
            <mesh geometry={nodes.Plane_Black_0.geometry} material={materials.Black} />
            <mesh geometry={nodes.Plane_White_0.geometry} material={materials.White} />
          </group>
          <mesh geometry={nodes.Plane001_Gray_0.geometry} material={materials.Gray} position={[-0.024, 447.864, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[85.224, 347.306, 96.52]} />
          <mesh geometry={nodes.Plane002_White_0.geometry} material={materials.White} position={[85.914, 372.237, 0]} rotation={[-Math.PI / 2, 0.38, 0]} scale={[85.224, 347.306, 65.686]} />
          <mesh geometry={nodes.Plane003_Light_Gray_0.geometry} material={materials.Light_Gray} position={[46.458, 404.458, -1.901]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane004_Light_Gray_0.geometry} material={materials.Light_Gray} position={[46.458, 404.458, 271.326]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane005_Light_Gray_0.geometry} material={materials.Light_Gray} position={[46.458, 404.458, -269.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[28.524, 2.747, 114.554]} />
          <mesh geometry={nodes.Plane006_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, -41.28]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane007_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, 39.563]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane008_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, 121.084]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane009_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, 204.062]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane010_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, -126.167]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane011_Light_Gray_0.geometry} material={materials.Light_Gray} position={[35.161, 388.225, -210.961]} rotation={[-Math.PI / 2, 0, 0]} scale={[30.984, 1.913, 118.787]} />
          <mesh geometry={nodes.Plane012_Black_0.geometry} material={materials.Black} position={[104.789, 415.661, -327.121]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[7.978, 11.987, 29.106]} />
          <mesh geometry={nodes.Plane013_Black_0.geometry} material={materials.Black} position={[105.845, 419.317, -271.105]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[2.635, 10.971, 9.614]} />
          <mesh geometry={nodes.Plane014_Black_0.geometry} material={materials.Black} position={[103.458, 411.232, -271.105]} rotation={[Math.PI / 2, 1.273, -Math.PI]} scale={[2.635, 10.971, 9.614]} />
          <mesh geometry={nodes.Plane015_Green_0.geometry} material={materials.Green} position={[105.845, 419.317, -245.105]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[1.808, 5.31, 8.918]} />
          <mesh geometry={nodes.Plane016_Red_0.geometry} material={materials.material} position={[103.669, 411.398, -245.105]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[1.808, 5.31, 8.918]} />
          <mesh geometry={nodes.Plane017_Black_0.geometry} material={materials.Black} position={[104.789, 415.661, -221.507]} rotation={[Math.PI / 2, 1.273, Math.PI]} scale={[4.437, 4.883, 16.188]} />
          <mesh geometry={nodes.Text_Yellow_0.geometry} material={materials.Yellow} position={[104.965, 415.11, -326.39]} rotation={[Math.PI / 2, 1.277, -Math.PI / 2]} scale={16.971} />
        </group>
      </group>
      <group position={[-6.79, 2.026, -9.066]} rotation={[-Math.PI / 2, 0, 3.131]} scale={[7.461, 7.461, 13.491]}>
        <mesh geometry={nodes.Base_Base_Texture_0002.geometry} material={materials['SVGMat.005']} position={[0, 0, -0.014]} scale={[0.267, 0.271, 0.129]} />
        <mesh geometry={nodes.Base_Base_Texture_0007.geometry} material={materials['SVGMat.034']} position={[0, 0.02, -0.015]} scale={[0.264, 0.237, 0.131]} />
        <mesh geometry={nodes.Plane069.geometry} material={materials['SVGMat.026']} position={[-0.016, 0, 0.02]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.011, 0.006, 0.011]} />
        <mesh geometry={nodes.Roundcube001_0.geometry} material={materials['SVGMat.026']} position={[0, 0, 0.043]} rotation={[3.139, -0.014, -0.618]} scale={[0.008, 0.008, 0.005]} />
        <mesh geometry={nodes.Vert005.geometry} material={materials['SVGMat.026']} position={[0.002, 0, 0.035]} rotation={[1.705, 0.176, -0.446]} scale={[0.182, 0.158, 0.109]} />
      </group>
      <group position={[-6.382, 2.029, -9.061]} rotation={[-Math.PI / 2, 0, 3.131]} scale={[9.564, 9.564, 17.293]}>
        <mesh geometry={nodes.Base_Base_Texture_0004.geometry} material={materials['SVGMat.005']} position={[0, 0, -0.012]} scale={[0.199, 0.199, 0.11]} />
        <mesh geometry={nodes.Base_Base_Texture_0006.geometry} material={materials['SVGMat.034']} position={[0, 0.015, -0.012]} scale={[0.199, 0.199, 0.11]} />
        <mesh geometry={nodes.Plane070.geometry} material={materials['SVGMat.027']} position={[-0.011, 0, 0.022]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.001} />
        <mesh geometry={nodes.Plane071.geometry} material={materials['SVGMat.004']} position={[-0.015, -0.001, 0.014]} rotation={[-0.001, -0.117, 3.125]} scale={[-0.001, -0.022, -0.012]} />
        <mesh geometry={nodes.Plane073.geometry} material={materials['SVGMat.009']} position={[-0.015, -0.014, 0.023]} rotation={[1.583, -0.077, 0.117]} scale={[0.002, 0.014, 0.018]} />
        <mesh geometry={nodes.Plane074.geometry} material={materials['SVGMat.004']} position={[0.016, 0, 0.013]} rotation={[-0.057, -0.004, 0.001]} scale={[-0.001, -0.022, -0.012]} />
        <mesh geometry={nodes.Plane075.geometry} material={materials['SVGMat.009']} position={[0.015, 0.014, 0.023]} rotation={[-1.628, -0.003, 3.137]} scale={[0.002, 0.015, 0.018]} />
        <mesh geometry={nodes.Plane076.geometry} material={materials['SVGMat.004']} position={[-0.017, -0.008, 0.023]} rotation={[-1.559, 0.077, -0.117]} scale={[-0.001, -0.014, -0.01]} />
        <mesh geometry={nodes.Plane077.geometry} material={materials['SVGMat.004']} position={[0.017, 0.008, 0.023]} rotation={[1.513, 0.003, -3.137]} scale={[-0.001, -0.015, -0.01]} />
        <mesh geometry={nodes.Plane078.geometry} material={materials['SVGMat.009']} position={[0.017, -0.01, 0.024]} rotation={[-1.628, -0.003, -0.004]} scale={[-0.001, -0.015, -0.014]} />
        <mesh geometry={nodes.Plane079.geometry} material={materials['SVGMat.009']} position={[-0.017, 0.009, 0.023]} rotation={[1.583, -0.077, -3.024]} scale={[-0.001, -0.014, -0.014]} />
        <mesh geometry={nodes.Roundcube001_0001.geometry} material={materials['SVGMat.027']} position={[0, 0, 0.039]} rotation={[3.139, -0.014, -0.618]} scale={[0.006, 0.006, 0.004]} />
        <mesh geometry={nodes.Vert002.geometry} material={materials['SVGMat.027']} position={[0.002, 0, 0.033]} rotation={[1.705, 0.176, -0.446]} scale={[0.126, 0.109, 0.075]} />
      </group>
      <group position={[4.922, 3.101, -9.061]} rotation={[-Math.PI / 2, 0, 3.131]} scale={[10.613, 10.613, 19.191]}>
        <mesh geometry={nodes.Base_Base_Texture_0001.geometry} material={materials['SVGMat.005']} position={[0, 0, -0.012]} scale={[0.199, 0.199, 0.11]} />
        <mesh geometry={nodes.Base_Base_Texture_0003.geometry} material={materials['SVGMat.034']} position={[0, 0.015, -0.012]} scale={[0.199, 0.199, 0.11]} />
        <mesh geometry={nodes.Plane080.geometry} material={materials['SVGMat.027']} position={[-0.011, 0, 0.022]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.001} />
        <mesh geometry={nodes.Plane081.geometry} material={materials['SVGMat.004']} position={[-0.015, -0.001, 0.014]} rotation={[-0.001, -0.117, 3.125]} scale={[-0.001, -0.022, -0.012]} />
        <mesh geometry={nodes.Plane082.geometry} material={materials['SVGMat.009']} position={[-0.015, -0.014, 0.023]} rotation={[1.583, -0.077, 0.117]} scale={[0.002, 0.014, 0.018]} />
        <mesh geometry={nodes.Plane083.geometry} material={materials['SVGMat.004']} position={[0.016, 0, 0.013]} rotation={[-0.057, -0.004, 0.001]} scale={[-0.001, -0.022, -0.012]} />
        <mesh geometry={nodes.Plane084.geometry} material={materials['SVGMat.009']} position={[0.015, 0.014, 0.023]} rotation={[-1.628, -0.003, 3.137]} scale={[0.002, 0.015, 0.018]} />
        <mesh geometry={nodes.Plane085.geometry} material={materials['SVGMat.004']} position={[-0.017, -0.008, 0.023]} rotation={[-1.559, 0.077, -0.117]} scale={[-0.001, -0.014, -0.01]} />
        <mesh geometry={nodes.Plane086.geometry} material={materials['SVGMat.004']} position={[0.017, 0.008, 0.023]} rotation={[1.513, 0.003, -3.137]} scale={[-0.001, -0.015, -0.01]} />
        <mesh geometry={nodes.Plane087.geometry} material={materials['SVGMat.009']} position={[0.017, -0.01, 0.024]} rotation={[-1.628, -0.003, -0.004]} scale={[-0.001, -0.015, -0.014]} />
        <mesh geometry={nodes.Plane088.geometry} material={materials['SVGMat.009']} position={[-0.017, 0.009, 0.023]} rotation={[1.583, -0.077, -3.024]} scale={[-0.001, -0.014, -0.014]} />
        <mesh geometry={nodes.Roundcube001_0002.geometry} material={materials['SVGMat.027']} position={[0, 0, 0.039]} rotation={[3.139, -0.014, -0.618]} scale={[0.006, 0.006, 0.004]} />
        <mesh geometry={nodes.Vert007.geometry} material={materials['SVGMat.027']} position={[0.002, 0, 0.033]} rotation={[1.705, 0.176, -0.446]} scale={[0.126, 0.109, 0.075]} />
      </group>
      <group position={[-9.69, 0.926, -8.616]} rotation={[-Math.PI / 2, 0, 1.574]} scale={[0.034, 0.031, 0.034]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.FACEPLATElo_res02001_Baked_FACEPLATElo_res02001_Bake1.geometry} material={materials['FACE.PLATE.lo_res02.001_Bake1_baked']} position={[0, 0.009, -0.148]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.glass__0.geometry} material={materials.glass__0} position={[0, 0.009, -0.148]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes.big_door.geometry} material={materials['Material.017']} position={[10.64, 3.255, -7.441]} rotation={[0, 1.57, 0]} scale={[2.122, 3.262, 0.188]}>
        <mesh geometry={nodes.cot016.geometry} material={materials['SVGMat.029']} position={[0.048, -0.176, 0.646]} scale={[0.103, 1, 1]} />
        <mesh geometry={nodes.Cube132.geometry} material={materials['Material.017']} position={[0.656, 0.805, 0.317]} rotation={[1.572, -0.001, -1.569]} scale={[-1.857, -0.178, -0.055]} />
        <mesh geometry={nodes.Cube133.geometry} material={materials['Material.017']} position={[-0.647, 0.805, 0.313]} rotation={[1.572, -0.001, -1.569]} scale={[-1.857, -0.178, -0.055]} />
        <mesh geometry={nodes.Cube134.geometry} material={materials['Material.017']} position={[-0.016, 0.805, 0.315]} rotation={[1.572, -0.001, -1.569]} scale={[-1.857, -0.178, -0.055]} />
        <mesh geometry={nodes.Cube135.geometry} material={materials['SVGMat.029']} position={[-0.054, -0.328, 0.278]} rotation={[1.271, -0.354, 2.654]} scale={[0.09, 0.631, 0.036]} />
        <mesh geometry={nodes.Cube137.geometry} material={materials['SVGMat.029']} position={[-0.054, -0.328, 0.278]} rotation={[1.271, -0.354, 2.654]} scale={[0.09, 0.631, 0.036]} />
        <mesh geometry={nodes.door.geometry} material={materials['Material.017']} position={[0.788, 0, 0.285]} />
        <mesh geometry={nodes.door_knob.geometry} material={materials['SVGMat.029']} position={[-0.054, -0.328, 0.278]} rotation={[1.271, -0.354, 2.654]} scale={[0.09, 0.631, 0.036]} />
        <mesh geometry={nodes.door001.geometry} material={materials['Material.017']} position={[0.007, 0, 0.282]} />
        <mesh geometry={nodes.Plane072.geometry} material={materials['SVGMat.029']} position={[-0.054, -0.328, 0.278]} rotation={[1.571, 0.001, -3.14]} scale={[0.056, 0.635, 0.036]} />
      </mesh>
      <mesh geometry={nodes.sofa010.geometry} material={materials.Material} position={[-5.06, 0.599, 1.778]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube168.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube169.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube170.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube171.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe010.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa008.geometry} material={materials.Material} position={[-5.06, 0.599, 5.512]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube080.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube081.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube082.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube083.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe013.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa004.geometry} material={materials.Material} position={[-5.06, 0.599, -0.85]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube084.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube085.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube086.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube087.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe011.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa005.geometry} material={materials.Material} position={[-5.06, 0.599, -4.561]} rotation={[-Math.PI, 0.004, -Math.PI]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube088.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube089.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube090.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube091.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe012.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa001.geometry} material={materials.Material} position={[5.113, 0.599, -0.839]} rotation={[0, -0.001, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe001.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa002.geometry} material={materials.Material} position={[5.101, 0.599, -4.573]} rotation={[0, -0.001, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube017.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube019.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube021.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe002.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa003.geometry} material={materials.Material} position={[5.122, 0.599, 1.79]} rotation={[0, -0.001, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube022.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube023.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube024.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe003.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa006.geometry} material={materials.Material} position={[5.134, 0.599, 5.501]} rotation={[0, -0.001, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube027.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube028.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube029.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe004.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa007.geometry} material={materials.Material} position={[-1.844, 0.599, 8.492]} rotation={[0, -1.57, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube033.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube034.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube035.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube036.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe005.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.sofa009.geometry} material={materials.Material} position={[1.89, 0.599, 8.474]} rotation={[0, -1.57, 0]} scale={[0.936, 0.229, 1.021]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.Material} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
        <mesh geometry={nodes.Cube038.geometry} material={materials.Material} position={[0.691, 1.889, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -0.938, -0.969]} />
        <mesh geometry={nodes.Cube039.geometry} material={materials.Material} position={[0.704, 3.841, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.234, -1.024, -1.144]} />
        <mesh geometry={nodes.Cube040_1.geometry} material={materials.Material} position={[-0.041, -1.489, 0]} scale={[0.772, 0.705, 1.116]} />
        <mesh geometry={nodes.thanh_ghe006.geometry} material={materials['Material.017']} position={[0.047, 0.218, -1.129]} scale={[0.898, 2.699, 0.161]} />
      </mesh>
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} position={[3.93, 1.935, 12.355]} rotation={[0, 0, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube078.geometry} material={nodes.Cube078.material} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube079_1.geometry} material={nodes.Cube079_1.material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane090.geometry} material={materials.Material} position={[-10.198, 1.935, 5.067]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube045.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube046_1.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane092_1.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane096.geometry} material={materials.Material} position={[-10.198, 1.935, 3.771]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube047.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube048.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane097.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane098.geometry} material={materials.Material} position={[-10.198, 1.935, 2.496]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube180_1.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube181.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane099.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane100.geometry} material={materials.Material} position={[-10.198, 1.935, 1.2]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube182_1.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube183.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane101.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane102.geometry} material={materials.Material} position={[-10.198, 1.935, -0.055]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube184.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube185.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane103.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane104.geometry} material={materials.Material} position={[-10.198, 1.935, -1.35]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube186.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube187.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane105.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane106.geometry} material={materials.Material} position={[-10.198, 1.935, -2.646]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube188.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube189.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane107.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane108.geometry} material={materials.Material} position={[-10.198, 1.935, -3.942]} rotation={[Math.PI, -0.002, Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube190_1.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube191.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane109.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane018.geometry} material={materials.Material} position={[10.651, 1.935, -1.245]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube044.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane019.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane020.geometry} material={materials.Material} position={[10.646, 1.935, 0.03]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube055.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube056.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane021.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane022.geometry} material={materials.Material} position={[10.642, 1.935, 1.326]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube057.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube058.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane023.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane024.geometry} material={materials.Material} position={[10.637, 1.935, 2.581]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube059.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube060.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane025.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane026.geometry} material={materials.Material} position={[10.633, 1.935, 3.877]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube061_1.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube062.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane027.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane028.geometry} material={materials.Material} position={[10.628, 1.935, 5.172]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube092.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube093.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane029.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Plane030.geometry} material={materials.Material} position={[10.624, 1.935, 6.468]} rotation={[0, -0.001, -Math.PI / 2]} scale={[0.714, 0.748, 0.611]}>
        <mesh geometry={nodes.Cube094_1.geometry} material={materials['Material.017']} position={[1.998, -1.358, -0.817]} rotation={[0, 0, Math.PI / 2]} scale={[0.101, 0.656, 0.124]} />
        <mesh geometry={nodes.Cube095.geometry} material={materials.Material} position={[1.334, -0.706, -0.001]} rotation={[0, 0, Math.PI / 2]} scale={[0.817, 0.152, 1]} />
        <mesh geometry={nodes.Plane031.geometry} material={materials['Material.017']} position={[0.367, 0.136, 0.001]} />
      </mesh>
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.017']} position={[5.102, 0.571, -2.729]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.072, 0.602, 0.062]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['Material.017']} position={[0.001, 0.01, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.074, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.333]} rotation={[0, 0, Math.PI / 2]} scale={[1, 7.719, 0.197]} />
      </mesh>
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.017']} position={[0.026, 0.571, 0.412]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.171, 0.96, 0.062]}>
        <mesh geometry={nodes.Cube030.geometry} material={materials['Material.017']} position={[0.001, 0.513, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.035, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.304]} rotation={[0, 0, Math.PI / 2]} scale={[0.981, 7.467, 0.197]} />
        <mesh geometry={nodes.Cube154_1.geometry} material={materials['Material.017']} position={[0.001, -0.49, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.035, 0.417, 7.707]} />
      </mesh>
      <mesh geometry={nodes.Cube051.geometry} material={materials['Material.017']} position={[-5.038, 0.571, 3.643]} rotation={[Math.PI / 2, 0, 1.575]} scale={[0.072, 0.602, 0.062]}>
        <mesh geometry={nodes.Cube049_1.geometry} material={materials['Material.017']} position={[0.001, 0.01, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.074, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.333]} rotation={[0, 0, Math.PI / 2]} scale={[1, 7.719, 0.197]} />
      </mesh>
      <mesh geometry={nodes.Cube054.geometry} material={materials['Material.017']} position={[-5.014, 0.571, -2.726]} rotation={[Math.PI / 2, 0, 1.575]} scale={[0.072, 0.602, 0.062]}>
        <mesh geometry={nodes.Cube052.geometry} material={materials['Material.017']} position={[0.001, 0.01, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.074, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube053.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.333]} rotation={[0, 0, Math.PI / 2]} scale={[1, 7.719, 0.197]} />
      </mesh>
      <mesh geometry={nodes.Cube065.geometry} material={materials['Material.017']} position={[0.01, 0.58, 8.251]} rotation={[Math.PI / 2, 0, -0.001]} scale={[0.072, 0.602, 0.062]}>
        <mesh geometry={nodes.Cube063.geometry} material={materials['Material.017']} position={[0.001, 0.01, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.074, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube064.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.333]} rotation={[0, 0, Math.PI / 2]} scale={[1, 7.719, 0.197]} />
      </mesh>
      <mesh geometry={nodes.Cube119.geometry} material={materials['Material.017']} position={[5.125, 0.571, 3.64]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.072, 0.602, 0.062]}>
        <mesh geometry={nodes.Cube117.geometry} material={materials['Material.017']} position={[0.001, 0.01, 4.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.074, 0.417, 7.707]} />
        <mesh geometry={nodes.Cube118.geometry} material={materials['Material.023']} position={[-0.008, 0.016, -7.333]} rotation={[0, 0, Math.PI / 2]} scale={[1, 7.719, 0.197]} />
      </mesh>
      <mesh geometry={nodes.blue_table_.geometry} material={materials['SVGMat.004']} position={[9.46, 1.671, -3.476]} rotation={[Math.PI, -0.006, Math.PI]} scale={[2.403, 2.603, 2.817]}>
        <mesh geometry={nodes.Cube129.geometry} material={materials['Material.017']} position={[-0.265, -0.351, 0.428]} rotation={[-Math.PI, 0.006, -Math.PI]} scale={[0.033, 0.307, 0.028]} />
      </mesh>
      <mesh geometry={nodes.ke_tuong_2.geometry} material={materials['Material.017']} position={[5.889, 2.263, -9.191]} rotation={[-Math.PI / 2, 0, 1.571]} scale={[0.348, 1.38, 0.062]}>
        <mesh geometry={nodes.Cube098.geometry} material={materials['Material.017']} position={[-0.654, 0.479, -20.956]} rotation={[-0.771, 1.568, 2.348]} scale={[0.48, 11.921, 0.214]} />
        <mesh geometry={nodes.Cube099.geometry} material={materials['Material.017']} position={[-0.08, 0, 76.44]} scale={[1.102, 1.109, 3.123]} />
        <mesh geometry={nodes.Cube101.geometry} material={materials['Material.017']} position={[-0.654, -0.48, -20.956]} rotation={[-0.771, 1.568, 2.348]} scale={[0.48, 11.921, 0.214]} />
        <mesh geometry={nodes.Cube110.geometry} material={materials['Material.017']} position={[0.004, 0, 27.744]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube111.geometry} material={materials['Material.017']} position={[0.004, 0, 42.718]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube112.geometry} material={materials['Material.017']} position={[0.004, 0, 58.749]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube113.geometry} material={materials['Material.017']} position={[0.004, 0, 9.758]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube114.geometry} material={materials['Material.017']} position={[0.004, 0, 0.952]} rotation={[1.571, -0.019, 0.02]} scale={[1.001, 8.454, 0.013]} />
        <mesh geometry={nodes.Cube115.geometry} material={materials['Material.017']} position={[0.004, 0, 35.096]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 7.259, 0.013]} />
        <mesh geometry={nodes.Cube116.geometry} material={materials['Material.017']} position={[-0.446, 0.908, 76.454]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.06, -0.152, -2.045]} />
        <mesh geometry={nodes.Cube130_1.geometry} material={materials['Material.017']} position={[-0.375, 0.008, 76.454]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.135, -0.163, -2.191]} />
      </mesh>
      <mesh geometry={nodes.Cube124.geometry} material={materials['Material.017']} position={[-10.018, 1.589, -8.139]} scale={[0.426, 0.042, 1.449]}>
        <mesh geometry={nodes.Cube120.geometry} material={materials['Material.017']} position={[-0.023, -17.662, 0.623]} scale={[0.948, 17.515, 0.362]} />
        <mesh geometry={nodes.Cube125_1.geometry} material={materials['Material.017']} position={[-0.026, -35.584, 0.001]} scale={[1.036, 1.683, 1]} />
        <mesh geometry={nodes.Cube126.geometry} material={materials['Material.017']} position={[-0.023, -17.662, -0.966]} rotation={[0, 0, -Math.PI]} scale={[-0.948, -17.659, -0.01]} />
        <mesh geometry={nodes.Cube127.geometry} material={materials['Material.017']} position={[0, -30.021, -0.348]} scale={[0.927, 3.985, 0.606]} />
        <mesh geometry={nodes.Cube128.geometry} material={materials['Material.017']} position={[-0.917, -18.084, 0]} scale={[0.047, 17.515, 0.972]} />
        <mesh geometry={nodes.Plane032.geometry} material={materials['Material.017']} position={[0.882, -30.062, -0.345]} rotation={[0, 0, -Math.PI / 2]} scale={[2.223, 0.595, 0.126]} />
      </mesh>
      <mesh geometry={nodes.ke_tuong_2001.geometry} material={materials['Material.017']} position={[-6.1, 2.263, -9.191]} rotation={[-Math.PI / 2, 0, 1.571]} scale={[0.348, 1.38, 0.062]}>
        <mesh geometry={nodes.Cube097.geometry} material={materials['Material.017']} position={[-0.654, 0.479, -20.956]} rotation={[-0.771, 1.568, 2.348]} scale={[0.48, 11.921, 0.214]} />
        <mesh geometry={nodes.Cube100.geometry} material={materials['Material.017']} position={[-0.08, 0, 76.44]} scale={[1.102, 1.109, 3.123]} />
        <mesh geometry={nodes.Cube102.geometry} material={materials['Material.017']} position={[-0.654, -0.48, -20.956]} rotation={[-0.771, 1.568, 2.348]} scale={[0.48, 11.921, 0.214]} />
        <mesh geometry={nodes.Cube103.geometry} material={materials['Material.017']} position={[0.004, 0, 27.744]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube104.geometry} material={materials['Material.017']} position={[0.004, 0, 42.718]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube105.geometry} material={materials['Material.017']} position={[0.004, 0, 58.749]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube106.geometry} material={materials['Material.017']} position={[0.004, 0, 9.758]} scale={[1, 1, 0.389]} />
        <mesh geometry={nodes.Cube107.geometry} material={materials['Material.017']} position={[0.004, 0, 0.952]} rotation={[1.571, -0.019, 0.02]} scale={[1.001, 8.454, 0.013]} />
        <mesh geometry={nodes.Cube108.geometry} material={materials['Material.017']} position={[0.004, 0, 35.096]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 7.259, 0.013]} />
        <mesh geometry={nodes.Cube109.geometry} material={materials['Material.017']} position={[-0.446, 0.908, 76.454]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.06, -0.152, -2.045]} />
        <mesh geometry={nodes.Cube131.geometry} material={materials['Material.017']} position={[-0.375, 0.008, 76.454]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.135, -0.163, -2.191]} />
      </mesh>
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.029']} position={[0.44, 4.53, 9.93]} rotation={[-1.571, 0, 0]} scale={-129.461}>
        <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.029']} position={[0.002, 0, -0.005]} scale={0.88} />
        <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.029']} position={[0.002, 0, 0.005]} />
        <mesh geometry={nodes.Curve003.geometry} material={materials['SVGMat.029']} position={[0.002, 0, 0.007]} />
      </mesh>
      <mesh geometry={nodes.Cube096.geometry} material={materials['SVGMat.027']} position={[0.014, 4.192, 10.012]} scale={[5.094, 2.789, 0.065]} />
      <mesh geometry={nodes.Cube123.geometry} material={materials['SVGMat.006']} position={[0.014, 4.192, 9.996]} scale={[5.094, 2.789, 0.105]} />
      <mesh geometry={nodes.LOGO.geometry} material={materials['Material.016']} position={[0.039, 6.094, 9.872]} rotation={[-Math.PI / 2, 0, 0]} scale={0.419} />
      <mesh geometry={nodes.Cube121.geometry} material={materials['Material.017']} position={[-10.616, 5.798, -4.518]} rotation={[0, Math.PI / 2, 0]} scale={[5.036, 0.083, 0.075]} />
      <mesh geometry={nodes.Cube122.geometry} material={materials['Material.017']} position={[-10.671, 5.815, 5.606]} rotation={[0, Math.PI / 2, 0]} scale={[3.702, 0.083, 0.075]} />
      <group position={[-10.591, 2.462, -4.46]} rotation={[-Math.PI / 2, 0, -1.582]} scale={[0.018, 0.015, 0.02]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.020']} />
      </group>
      <group position={[-10.59, 2.509, 5.626]} rotation={[-Math.PI / 2, 0, 1.564]} scale={[0.018, 0.015, 0.02]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_3_1.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.fan.geometry} material={materials['BOTTUNS.001']} position={[-9.554, 2.551, -5.544]} rotation={[0, -0.038, -Math.PI / 2]} scale={0.416}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['BOTTUNS.001']} position={[3.665, -1.232, 0.016]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.292, 0.802, 1.292]} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['BOTTUNS.001']} position={[2.063, -1.584, 0.022]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.292, 0.802, 1.292]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.base} position={[2.433, -0.995, 0.022]} rotation={[0, 1.571, 0]} scale={0.043} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.base} position={[2.57, -0.995, 0.022]} rotation={[0, 1.571, 0]} scale={0.043} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.base} position={[2.715, -0.995, 0.022]} rotation={[0, 1.571, 0]} scale={0.043} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.base} position={[2.852, -0.995, 0.022]} rotation={[0, 1.571, 0]} scale={0.043} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['BOTTUNS.001']} position={[0.056, -0.867, 0.02]} rotation={[0, 1.571, 0]} scale={0.447} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['BOTTUNS.001']} position={[0.019, -1.723, 0.026]} rotation={[0, 1.571, 0]} scale={0.447} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['BOTTUNS.001']} position={[0, -0.44, 0.022]} rotation={[0, 1.571, 0]} scale={0.447} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['BOTTUNS.001']} position={[0.003, -0.008, 0]} rotation={[0, 1.571, 0]} scale={[1.621, 2.205, 1.621]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['BOTTUNS.001']} position={[-0.001, 0.526, 0]} rotation={[0, 1.571, 0]} scale={[0.117, 0.037, 0.117]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['BOTTUNS.001']} position={[-0.493, -1.612, 0.023]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.029, 0.042, 0.029]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['BOTTUNS.001']} position={[-0.81, -0.04, 0.026]} rotation={[Math.PI, 1.571, 0]} scale={[0.352, 0.309, 0.289]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['BOTTUNS.001']} position={[-0.246, -0.04, 0.795]} rotation={[Math.PI, Math.PI / 10, 0]} scale={[0.352, 0.309, 0.289]} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['BOTTUNS.001']} position={[5.575, -3.454, 0.027]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-0.004, 0, -0.004]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['BOTTUNS.001']} position={[0.658, -0.04, 0.473]} rotation={[-Math.PI, -0.942, 0]} scale={[0.352, 0.309, 0.289]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['BOTTUNS.001']} position={[0.654, -0.04, -0.479]} rotation={[0, -0.942, -Math.PI]} scale={[0.352, 0.309, 0.289]} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['BOTTUNS.001']} position={[-0.254, -0.04, -0.747]} rotation={[0, Math.PI / 10, Math.PI]} scale={[0.352, 0.309, 0.289]} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['BOTTUNS.001']} position={[-0.212, -1.755, 0.023]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.029, 0.029, 0.028]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['BOTTUNS.001']} position={[0, -1.755, -0.19]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.029, 0.029, 0.028]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['BOTTUNS.001']} position={[0.213, -1.755, 0.022]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.029, 0.029, 0.028]} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['BOTTUNS.001']} position={[0.001, -1.755, 0.235]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.029, 0.029, 0.028]} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['BOTTUNS.001']} position={[-0.143, -0.16, 0.022]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.019} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['BOTTUNS.001']} position={[0, -0.16, 0.166]} rotation={[Math.PI / 2, 0, 0]} scale={0.019} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['BOTTUNS.001']} position={[0.144, -0.16, 0.023]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.019} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['BOTTUNS.001']} position={[5.575, -3.454, 0.027]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.004, 0, -0.004]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials['BOTTUNS.001']} position={[0.001, -0.16, -0.121]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.019} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['BOTTUNS.001']} position={[2.5, -1.007, 0.02]} rotation={[0, 1.571, 0]} scale={0.047} />
        <mesh geometry={nodes.Object_64.geometry} material={materials['BOTTUNS.001']} position={[2.646, -1.006, 0.039]} rotation={[0, 1.571, 0]} scale={0.047} />
        <mesh geometry={nodes.Object_66.geometry} material={materials['BOTTUNS.001']} position={[2.786, -1.006, 0.04]} rotation={[0, 1.571, 0]} scale={0.047} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['BOTTUNS.001']} position={[2.394, -1.225, 0.021]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.292, 0.802, 1.292]} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['BOTTUNS.001']} position={[2.38, -1.366, 0.023]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.292, 0.802, 1.292]} />
      </mesh>
      <group position={[10.589, 0, 8.998]} rotation={[-Math.PI / 2, 0, -2.298]} scale={0.923}>
        <mesh geometry={nodes['Material_003-material002'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['Material_003-material002_1'].geometry} material={materials['Material.003']} />
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material001'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material002'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material003'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material004'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material005'].geometry} material={materials['Material.005']} position={[1.045, 0, 5.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_003-material'].geometry} material={materials['Material.004']} />
        <mesh geometry={nodes['Material_003-material001'].geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Top.geometry} material={materials.Top} position={[7.272, 1.403, -0.58]} rotation={[Math.PI / 2, 0, 1.571]} scale={0.009}>
        <mesh geometry={nodes.Leg1.geometry} material={materials.legs} position={[0, 0, -10.948]} scale={[1, 1, 0.825]} />
        <mesh geometry={nodes.Leg2.geometry} material={materials.legs} position={[0, 0, -10.948]} scale={[1, 1, 0.825]} />
        <mesh geometry={nodes.Leg3.geometry} material={materials.legs} position={[0, 0, -10.948]} scale={[1, 1, 0.825]} />
        <mesh geometry={nodes.Leg4.geometry} material={materials.legs} position={[0, 0, -10.948]} scale={[1, 1, 0.825]} />
        <mesh geometry={nodes.Under.geometry} material={materials.Under} />
      </mesh>
      <mesh geometry={nodes.co_3.geometry} material={materials['Material.013']} position={[-8.907, 3.491, 8.316]} scale={[1, 1, 1.852]}>
        <mesh geometry={nodes['3'].geometry} material={materials['SVGMat.006']} position={[-0.038, -1.13, -0.05]} rotation={[Math.PI / 2, 0, 0]} scale={[60.788, 32.825, 60.788]}>
          <mesh geometry={nodes.Curve011_2.geometry} material={materials['SVGMat.001']} position={[-0.023, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
          <mesh geometry={nodes.Curve012_1.geometry} material={materials['SVGMat.006']} position={[-0.023, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
          <mesh geometry={nodes.Curve013_2.geometry} material={materials['SVGMat.006']} position={[0.025, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
        </mesh>
        <mesh geometry={nodes.Curve017.geometry} material={materials['SVGMat.028']} position={[-0.067, -1.803, -0.146]} rotation={[Math.PI / 2, 0, 0]} scale={[34.943, 36.738, 45.297]} />
        <mesh geometry={nodes.Curve018.geometry} material={materials['SVGMat.028']} position={[0.959, -0.758, -0.142]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[29.069, 36.738, 45.297]} />
        <mesh geometry={nodes.Curve019.geometry} material={materials['SVGMat.028']} position={[-0.949, -0.779, -0.14]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[28.607, 36.738, 45.297]} />
        <mesh geometry={nodes.Curve020.geometry} material={materials['SVGMat.028']} position={[-0.053, -1.936, 0.273]} rotation={[0.805, 0, 0]} scale={[34.943, 53.285, 37.303]} />
        <mesh geometry={nodes.Curve140.geometry} material={materials['SVGMat.028']} position={[-0.022, -1.803, -0.146]} rotation={[Math.PI / 2, 0, 0]} scale={[34.943, 36.738, 45.297]} />
        <mesh geometry={nodes.Curve141.geometry} material={materials['SVGMat.028']} position={[-0.09, -1.803, -0.146]} rotation={[Math.PI / 2, 0, 0]} scale={[34.943, 36.738, 45.297]} />
      </mesh>
      <mesh geometry={nodes.co_2.geometry} material={materials['Material.012']} position={[-5.628, 2.305, 8.256]} rotation={[-0.022, 0, 0]} scale={[0.988, 0.803, 0.988]}>
        <mesh geometry={nodes['2'].geometry} material={materials['SVGMat.006']} position={[-0.05, 0.07, 0.006]} rotation={[1.594, 0, 0]} scale={[61.539, 61.552, 75.672]}>
          <mesh geometry={nodes.Curve008_1.geometry} material={materials['SVGMat.001']} position={[-0.023, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
          <mesh geometry={nodes.Curve009_1.geometry} material={materials['SVGMat.006']} position={[-0.023, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
          <mesh geometry={nodes.Curve010_1.geometry} material={materials['SVGMat.006']} position={[0.025, 0, 0.038]} rotation={[0, 0, -Math.PI / 2]} scale={[0.79, 2.133, 1]} />
        </mesh>
        <mesh geometry={nodes.Curve005.geometry} material={materials['SVGMat.028']} position={[-0.092, -1.092, -0.047]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Curve007_1.geometry} material={materials['SVGMat.028']} position={[-0.063, -1.092, -0.047]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Curve014.geometry} material={materials['SVGMat.028']} position={[0.968, 0.031, 0.004]} rotation={[1.593, -Math.PI / 2, 0]} scale={[35.205, 68.033, 45.297]} />
        <mesh geometry={nodes.Curve015.geometry} material={materials['SVGMat.028']} position={[-0.987, 0.031, 0.007]} rotation={[-3.107, 1.56, 1.561]} scale={[35.206, 68.036, 45.298]} />
        <mesh geometry={nodes.Curve016.geometry} material={materials['SVGMat.028']} position={[-0.079, -1.092, -0.034]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Vert001.geometry} material={nodes.Vert001.material} position={[1.33, 1.242, 0.025]} rotation={[0.023, 0, 0]} scale={[1.012, 1.245, 1.013]} />
      </mesh>
      <mesh geometry={nodes.co_1.geometry} material={materials['Material.012']} position={[8.292, 2.305, 8.256]} rotation={[-0.022, 0, 0]} scale={[0.988, 0.803, 0.988]}>
        <mesh geometry={nodes['1'].geometry} material={materials['SVGMat.006']} position={[-0.073, 0.07, 0.006]} rotation={[1.594, 0, 0]} scale={[61.539, 61.552, 75.672]} />
        <mesh geometry={nodes.Curve004.geometry} material={materials['SVGMat.006']} position={[-1.518, -2.812, -0.046]} rotation={[1.594, 0.005, -1.575]} scale={[48.633, 131.239, 75.672]} />
        <mesh geometry={nodes.Curve006.geometry} material={materials['SVGMat.006']} position={[1.446, -2.812, -0.046]} rotation={[1.594, 0.005, -1.575]} scale={[48.633, 131.239, 75.672]} />
        <mesh geometry={nodes.Curve021.geometry} material={materials['SVGMat.028']} position={[-0.079, -1.092, -0.034]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Curve022.geometry} material={materials['SVGMat.028']} position={[0.968, 0.031, 0.004]} rotation={[-3.107, -1.56, 1.581]} scale={[35.206, 68.036, 45.298]} />
        <mesh geometry={nodes.Curve023.geometry} material={materials['SVGMat.028']} position={[-0.987, 0.031, 0.007]} rotation={[-3.107, 1.56, 1.561]} scale={[35.206, 68.036, 45.298]} />
        <mesh geometry={nodes.Curve133.geometry} material={materials['SVGMat.028']} position={[-0.105, -1.092, -0.034]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Curve134.geometry} material={materials['SVGMat.028']} position={[-0.053, -1.092, -0.048]} rotation={[1.594, 0, 0]} scale={[36.239, 68.036, 45.299]} />
        <mesh geometry={nodes.Vert006_1.geometry} material={materials['SVGMat.028']} position={[1.349, 1.242, 0.025]} rotation={[0.023, 0, 0]} scale={[1.012, 1.245, 1.013]} />
      </mesh>
      <mesh geometry={nodes.khung_1.geometry} material={nodes.khung_1.material} position={[-5.534, 2.906, -9.101]} rotation={[2.929, 0, Math.PI]} scale={[0.661, 0.939, 0.053]}>
        <mesh geometry={nodes.cot012.geometry} material={materials['SVGMat.029']} position={[0, 0.002, 0.146]} />
      </mesh>
      <mesh geometry={nodes.khung_2.geometry} material={nodes.khung_2.material} position={[-6.645, 2.906, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.693, 0.985, 0.055]}>
        <mesh geometry={nodes.cot010.geometry} material={materials['SVGMat.029']} position={[0, 0.005, 0.368]} />
      </mesh>
      <mesh geometry={nodes.khung_3.geometry} material={nodes.khung_3.material} position={[-6.706, 4.924, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.664, 0.956, 0.054]}>
        <mesh geometry={nodes.cot006.geometry} material={materials['SVGMat.029']} position={[0, 0.002, 0.165]} />
      </mesh>
      <mesh geometry={nodes.khung_4.geometry} material={nodes.khung_4.material} position={[-6.072, 5.894, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.568, 0.795, 0.047]}>
        <mesh geometry={nodes.cot004.geometry} material={materials['SVGMat.029']} position={[0, 0, 0.031]} />
      </mesh>
      <mesh geometry={nodes.cot009.geometry} material={nodes.cot009.material} position={[-5.412, 4.924, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.609, 0.842, 0.05]}>
        <mesh geometry={nodes.cot008.geometry} material={materials['SVGMat.029']} position={[0, 0, 0.029]} />
      </mesh>
      <mesh geometry={nodes.khung_3001.geometry} material={nodes.khung_3001.material} position={[5.264, 4.924, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.664, 0.956, 0.054]}>
        <mesh geometry={nodes.cot001.geometry} material={materials['SVGMat.029']} position={[0, 0.002, 0.165]} />
      </mesh>
      <mesh geometry={nodes.khung_3002.geometry} material={nodes.khung_3002.material} position={[6.591, 4.924, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.664, 0.956, 0.054]}>
        <mesh geometry={nodes.cot002.geometry} material={materials['SVGMat.029']} position={[0, 0.002, 0.165]} />
      </mesh>
      <mesh geometry={nodes.khung_3003.geometry} material={nodes.khung_3003.material} position={[5.905, 5.898, -8.97]} rotation={[2.895, 0, Math.PI]} scale={[0.635, 0.913, 0.051]}>
        <mesh geometry={nodes.cot003.geometry} material={materials['SVGMat.029']} position={[0, 0.002, 0.165]} />
      </mesh>
      <mesh geometry={nodes.Cube005_Power_box_0001.geometry} material={materials.Power_box} position={[10.817, 3.471, -4.061]} rotation={[-Math.PI / 2, 0, -3.136]} scale={[0.253, 0.307, 0.253]}>
        <mesh geometry={nodes.Cylinder003_Power_box_0001.geometry} material={materials.Power_box} position={[-0.035, -0.4, -0.434]} />
      </mesh>
      <mesh geometry={nodes.Cube005_Power_box_0002.geometry} material={materials.Power_box} position={[10.817, 3.471, -3.94]} rotation={[-Math.PI / 2, 0, -3.136]} scale={[0.253, 0.307, 0.253]}>
        <mesh geometry={nodes.Cylinder003_Power_box_0002.geometry} material={materials.Power_box} position={[-0.035, -0.4, -0.434]} />
      </mesh>
      <mesh geometry={nodes.Cube005_Power_box_0003.geometry} material={materials.Power_box} position={[10.817, 3.471, -3.819]} rotation={[-Math.PI / 2, 0, -3.136]} scale={[0.253, 0.307, 0.253]}>
        <mesh geometry={nodes.Cylinder003_Power_box_0003.geometry} material={materials.Power_box} position={[-0.035, -0.4, -0.434]} />
      </mesh>
      <mesh geometry={nodes.Cube136.geometry} material={nodes.Cube136.material} position={[10.834, 3.479, -3.945]} scale={[0.02, 0.287, 0.38]} />
      <mesh geometry={nodes.Cube138.geometry} material={nodes.Cube138.material} position={[10.846, 3.47, -3.945]} scale={[0.018, 0.253, 0.335]} />
      <mesh geometry={nodes.Cube139.geometry} material={materials['SVGMat.015']} position={[10.762, 3.479, -3.945]} scale={[0.02, 0.287, 0.38]} />
      <mesh geometry={nodes.Cube140.geometry} material={materials['Material.019']} position={[10.844, 3.297, -2.992]} scale={[0.009, 0.1, 0.075]} />
      <group position={[10.825, 3.325, -2.832]} scale={[0.017, 0.111, 0.041]}>
        <mesh geometry={nodes.Cube225.geometry} material={materials.BOTTUNS} />
        <mesh geometry={nodes.Cube225_1.geometry} material={materials.base} />
      </group>
      <mesh geometry={nodes.Cube150.geometry} material={materials.BOTTUNS} position={[10.852, 3.266, -2.833]} rotation={[-Math.PI, 0, 0]} scale={[-0.002, -0.032, -0.046]} />
      <mesh geometry={nodes.Object_4001.geometry} material={materials['Material.006']} position={[10.806, 3.341, -2.99]} rotation={[Math.PI / 2, 0, 1.577]} scale={0.221}>
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.007']} position={[-0.155, 0.096, 0.162]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_5001.geometry} material={materials['Material.007']} position={[0, 0.108, 0.162]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_5002.geometry} material={materials['Material.007']} position={[0.155, 0.12, 0.162]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_5003.geometry} material={materials['Material.007']} position={[-0.155, 0.096, 0.347]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_5004.geometry} material={materials['Material.007']} position={[0, 0.108, 0.347]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_5005.geometry} material={materials['Material.007']} position={[0.155, 0.12, 0.347]} scale={[1.494, 1.004, 1]} />
        <mesh geometry={nodes.Object_6001.geometry} material={materials['Material.008']} position={[0.176, 0.098, -0.265]} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.009']} position={[-0.102, 0.097, -0.134]} />
        <mesh geometry={nodes.Object_8001.geometry} material={materials['Material.010']} position={[-0.01, 0.105, -0.522]} />
        <mesh geometry={nodes.Object_9001.geometry} material={materials['Material.011']} position={[-0.162, 0.094, 0.13]} />
      </mesh>
      <mesh geometry={nodes.switch_.geometry} material={nodes.switch_.material} position={[10.838, 3.354, -3.406]} scale={[0.009, 0.164, 0.093]}>
        <mesh geometry={nodes.Cube141.geometry} material={nodes.Cube141.material} position={[-1.124, 0.466, -0.347]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube142.geometry} material={nodes.Cube142.material} position={[-1.124, 0.466, 0.338]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube143_1.geometry} material={nodes.Cube143_1.material} position={[-1.124, 0.025, -0.347]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube144_1.geometry} material={nodes.Cube144_1.material} position={[-1.124, 0.025, 0.338]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube145_1.geometry} material={nodes.Cube145_1.material} position={[-1.124, -0.429, -0.347]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube146_1.geometry} material={nodes.Cube146_1.material} position={[-1.124, -0.429, 0.338]} scale={[2.812, 0.147, 0.26]} />
        <mesh geometry={nodes.Cube147.geometry} material={nodes.Cube147.material} position={[-0.052, 0, 2.209]}>
          <mesh geometry={nodes.Cube149_1.geometry} material={nodes.Cube149_1.material} position={[-1.124, 0.466, -0.017]} scale={[2.812, 0.147, 0.26]} />
          <mesh geometry={nodes.Cube151_1.geometry} material={nodes.Cube151_1.material} position={[-1.124, 0.025, -0.017]} scale={[2.812, 0.147, 0.26]} />
          <mesh geometry={nodes.Cube153_1.geometry} material={nodes.Cube153_1.material} position={[-1.124, -0.429, -0.017]} scale={[2.812, 0.147, 0.26]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Curve024.geometry} material={materials.BOTTUNS} position={[8.676, 6.143, -9.521]} rotation={[1.571, 0, 0]} scale={38.915}>
        <mesh geometry={nodes.Cube152.geometry} material={nodes.Cube152.material} position={[0, -0.001, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.008, -0.001, -0.008]} />
        <mesh geometry={nodes.Curve025.geometry} material={materials['SVGMat.027']} position={[0, 0.001, -0.008]} />
        <mesh geometry={nodes.Curve026.geometry} material={materials['SVGMat.027']} position={[-0.009, 0.001, 0.009]} />
        <mesh geometry={nodes.Curve027.geometry} material={materials['SVGMat.027']} position={[-0.009, 0.001, 0.009]} />
        <mesh geometry={nodes.Curve028.geometry} material={materials['SVGMat.027']} position={[-0.009, 0.001, 0.009]} />
        <mesh geometry={nodes.Curve029.geometry} material={materials['SVGMat.027']} position={[-0.008, 0.001, 0]} rotation={[0, Math.PI / 2, 0]} />
      </mesh>
      <group position={[10.448, 4.858, 2.221]} rotation={[0, 1.571, 0]} scale={[0.826, 1.263, 0.074]}>
        <mesh geometry={nodes.Cube155_1.geometry} material={materials['SVGMat.029']} />
        <mesh geometry={nodes.Cube155_2.geometry} material={materials['SVGMat.013']} />
      </group>
      <group position={[10.448, 4.858, 0.493]} rotation={[0, 1.571, 0]} scale={[0.826, 1.263, 0.074]}>
        <mesh geometry={nodes.Cube157_1.geometry} material={materials['SVGMat.006']} />
        <mesh geometry={nodes.Cube157_2.geometry} material={materials['SVGMat.029']} />
        <mesh geometry={nodes.Cube157_3.geometry} material={materials['SVGMat.012']} />
      </group>
      <mesh geometry={nodes.Curve036.geometry} material={materials['SVGMat.028']} position={[10.486, 4.381, 2.224]} rotation={[Math.PI / 2, 0.001, 1.572]} scale={3.145}>
        <mesh geometry={nodes.Curve030.geometry} material={materials['SVGMat.029']} position={[0, 0.008, 0.058]} scale={1.012} />
        <mesh geometry={nodes.Curve031.geometry} material={materials['SVGMat.008']} position={[-0.026, 0.008, 0.005]} scale={1.001} />
        <mesh geometry={nodes.Curve032.geometry} material={materials['SVGMat.012']} position={[-0.049, 0.008, 0.079]} scale={1.001} />
        <mesh geometry={nodes.Curve033.geometry} material={materials['SVGMat.012']} position={[0.049, 0.008, 0.079]} scale={1.001} />
        <mesh geometry={nodes.Curve034.geometry} material={materials['SVGMat.012']} position={[0, 0.009, 0.108]} scale={1.001} />
        <mesh geometry={nodes.Curve035.geometry} material={materials['SVGMat.029']} position={[0.004, 0.012, 0.006]} rotation={[0, -0.113, 0]} scale={1.901} />
        <mesh geometry={nodes.Curve037.geometry} material={materials['SVGMat.012']} position={[0.003, 0.009, 0.006]} scale={1.001} />
        <mesh geometry={nodes.Curve038.geometry} material={materials['SVGMat.013']} position={[0.043, 0.008, 0.004]} scale={1.001} />
        <mesh geometry={nodes.Curve039.geometry} material={materials['SVGMat.029']} position={[0.008, -0.001, -0.429]} scale={[1.026, 1.001, 1.096]} />
        <mesh geometry={nodes.Curve040.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve041.geometry} material={materials['SVGMat.029']} position={[0, 0.009, 0.077]} scale={1.001} />
        <mesh geometry={nodes.Curve042.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve043.geometry} material={materials['SVGMat.016']} position={[-0.06, 0.008, 0.005]} scale={1.001} />
        <mesh geometry={nodes.Curve044.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve045.geometry} material={materials['SVGMat.033']} position={[0.008, 0.005, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve046.geometry} material={materials['SVGMat.033']} position={[-0.034, 0.003, -0.263]} scale={1.001} />
        <mesh geometry={nodes.Curve047.geometry} material={materials['SVGMat.033']} position={[0.048, 0.004, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve048.geometry} material={materials['SVGMat.008']} position={[-0.04, 0.008, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve049_1.geometry} material={materials['SVGMat.008']} position={[0.057, 0.008, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve050.geometry} material={materials['SVGMat.022']} position={[-0.041, 0.006, -0.262]} scale={1.001} />
        <mesh geometry={nodes.Curve051.geometry} material={materials['SVGMat.008']} position={[-0.041, 0.006, -0.262]} scale={1.001} />
        <mesh geometry={nodes.Curve052.geometry} material={materials['SVGMat.023']} position={[0.049, 0.008, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve053.geometry} material={materials['SVGMat.008']} position={[0.049, 0.008, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve054.geometry} material={materials['SVGMat.029']} position={[-0.004, 0.012, -0.265]} scale={1.001} />
        <mesh geometry={nodes.Curve055.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve056.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve057.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve058.geometry} material={materials['SVGMat.029']} position={[0.09, 0.012, -0.274]} scale={1.001} />
        <mesh geometry={nodes.Curve059.geometry} material={materials['SVGMat.029']} position={[0.056, 0.012, -0.427]} rotation={[0, -0.113, 0]} scale={1.001} />
        <mesh geometry={nodes.Curve060.geometry} material={materials['SVGMat.029']} position={[-0.04, 0.012, -0.427]} rotation={[0, -0.113, 0]} scale={1.001} />
        <mesh geometry={nodes.Curve061.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve062.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve063.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve064.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve065.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve066.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve067.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve068.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve069.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve070.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve071.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve072.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve073.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve074.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve075.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve076.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve077.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve078.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve079.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve080.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve081.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve082.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve083.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve084.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
      </mesh>
      <mesh geometry={nodes.Curve137.geometry} material={materials['SVGMat.028']} position={[10.486, 4.381, 0.475]} rotation={[Math.PI / 2, 0.001, 1.572]} scale={3.145}>
        <mesh geometry={nodes.Curve085.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve086.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve087.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve088.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve089.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve090.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve091.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve092.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve093.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve094.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.01, 0.117]} scale={4.795} />
        <mesh geometry={nodes.Curve095.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve096.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve097.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve098.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve099.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve100.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve101.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve102.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve103.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve104.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve105.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve106.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve107.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve108.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve109.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve110.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve111.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve112.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve113.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve114.geometry} material={materials['SVGMat.029']} position={[-0.093, 0.008, 0.112]} scale={4.795} />
        <mesh geometry={nodes.Curve115.geometry} material={materials['SVGMat.008']} position={[-0.026, 0.008, 0.005]} scale={1.001} />
        <mesh geometry={nodes.Curve116.geometry} material={materials['SVGMat.013']} position={[-0.049, 0.008, 0.079]} scale={1.001} />
        <mesh geometry={nodes.Curve117.geometry} material={materials['SVGMat.013']} position={[0.049, 0.008, 0.079]} scale={1.001} />
        <mesh geometry={nodes.Curve118.geometry} material={materials['SVGMat.013']} position={[0, 0.009, 0.108]} scale={1.001} />
        <mesh geometry={nodes.Curve119.geometry} material={materials['SVGMat.012']} position={[0.003, 0.009, 0.006]} scale={1.001} />
        <mesh geometry={nodes.Curve120.geometry} material={materials['SVGMat.013']} position={[0.043, 0.008, 0.004]} scale={1.001} />
        <mesh geometry={nodes.Curve121.geometry} material={materials['SVGMat.029']} position={[0, 0.009, 0.077]} scale={1.001} />
        <mesh geometry={nodes.Curve122.geometry} material={materials['SVGMat.016']} position={[-0.06, 0.008, 0.005]} scale={1.001} />
        <mesh geometry={nodes.Curve123.geometry} material={materials['SVGMat.019']} position={[0.008, 0.005, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve124.geometry} material={materials['SVGMat.019']} position={[-0.034, 0.003, -0.263]} scale={1.001} />
        <mesh geometry={nodes.Curve125.geometry} material={materials['SVGMat.019']} position={[0.048, 0.004, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve126.geometry} material={materials['SVGMat.008']} position={[-0.04, 0.008, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve127.geometry} material={materials['SVGMat.008']} position={[0.057, 0.008, -0.429]} scale={1.001} />
        <mesh geometry={nodes.Curve128.geometry} material={materials['SVGMat.022']} position={[-0.041, 0.006, -0.262]} scale={1.001} />
        <mesh geometry={nodes.Curve129.geometry} material={materials['SVGMat.008']} position={[-0.041, 0.006, -0.262]} scale={1.001} />
        <mesh geometry={nodes.Curve130.geometry} material={materials['SVGMat.023']} position={[0.049, 0.008, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve131.geometry} material={materials['SVGMat.008']} position={[0.049, 0.008, -0.259]} scale={1.001} />
        <mesh geometry={nodes.Curve132.geometry} material={materials['SVGMat.029']} position={[0.05, 0.011, -0.265]} scale={1.001} />
        <mesh geometry={nodes.Curve135.geometry} material={materials['SVGMat.029']} position={[0.008, 0.012, -0.427]} rotation={[0, -0.113, 0]} scale={1.001} />
        <mesh geometry={nodes.Curve136.geometry} material={materials['SVGMat.029']} position={[0.004, 0.012, 0.006]} rotation={[0, -0.113, 0]} scale={1.901} />
        <mesh geometry={nodes.Curve138.geometry} material={materials['SVGMat.029']} position={[0.008, -0.001, -0.429]} scale={[1.026, 1.001, 1.096]} />
        <mesh geometry={nodes.Curve139.geometry} material={materials['SVGMat.029']} position={[0, 0.008, 0.058]} scale={1.012} />
      </mesh>
      <mesh geometry={nodes.METAL_1.geometry} material={materials['SVGMat.026']} position={[-7.208, 2.075, -9.071]} rotation={[-Math.PI / 2, 0, 3.131]} scale={[6.818, 6.818, 12.329]}>
        <mesh geometry={nodes.Base_Base_Texture_0.geometry} material={materials['SVGMat.005']} position={[0, 0, -0.02]} scale={[0.267, 0.319, 0.176]} />
        <mesh geometry={nodes.Base_Base_Texture_0008_1.geometry} material={materials['SVGMat.034']} position={[0, 0.024, -0.022]} rotation={[-0.005, 0, 0]} scale={[0.264, 0.279, 0.197]} />
        <mesh geometry={nodes.Object_10001.geometry} material={materials['SVGMat.026']} position={[0, 0, 0.052]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.002, 0.001, 0.002]} />
        <mesh geometry={nodes.Vert003.geometry} material={materials['SVGMat.026']} position={[-0.015, 0, 0.03]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.096, 0.053, 0.096]} />
        <mesh geometry={nodes.Vert004.geometry} material={materials['SVGMat.026']} position={[0.002, 0, 0.043]} rotation={[1.705, 0.176, -0.446]} scale={[0.182, 0.158, 0.109]} />
      </mesh>
      <mesh geometry={nodes.WALL_.geometry} material={materials['Material.021']} position={[11.058, 4.193, -0.056]} rotation={[0, Math.PI / 2, 0]} scale={[9.912, 4.315, 0.188]} />
      <mesh geometry={nodes.WALL_001.geometry} material={materials['Material.021']} position={[0.08, 4.193, 9.815]} rotation={[Math.PI, 0, Math.PI]} scale={[11.153, 4.315, 0.29]} />
      <mesh geometry={nodes.WALL_002.geometry} material={materials['Material.021']} position={[-10.948, 4.193, -0.056]} rotation={[0, Math.PI / 2, 0]} scale={[9.912, 4.315, 0.188]} />
      <mesh geometry={nodes.WALL_003.geometry} material={materials['Material.021']} position={[0.063, 4.2, -9.792]} rotation={[Math.PI, 0, Math.PI]} scale={[11.153, 4.292, 0.188]} />
      <mesh geometry={nodes.WALL_004.geometry} material={materials['Material.021']} position={[-0.041, 1.148, -9.495]} rotation={[Math.PI, 0, Math.PI]} scale={[4.541, 1.175, 0.093]} />
      <mesh geometry={nodes.cot.geometry} material={materials['Material.021']} position={[-10.582, 3.585, 1.246]} rotation={[0, Math.PI / 2, 0]} scale={[0.549, 3.615, 0.188]} />
      <mesh geometry={nodes.wall_medal.geometry} material={materials['Material.021']} position={[10.719, 3.585, 1.358]} rotation={[0, Math.PI / 2, 0]} scale={[1.84, 3.615, 0.188]} />
      <mesh geometry={nodes.Cube155.geometry} material={materials['Material.024']} position={[0.113, -0.067, -0.043]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-10.887, -0.034, -9.737]} />
      <mesh geometry={nodes.CEILING.geometry} material={nodes.CEILING.material} position={[0.113, 7.591, -0.043]} rotation={[-Math.PI, 0, 0]} scale={[-10.887, -0.413, -9.737]} />
      <mesh geometry={nodes.Curve142.geometry} material={materials['SVGMat.035']} position={[-5.722, 4.285, -9.321]} rotation={[1.107, 0, Math.PI]} scale={[1.641, 0.787, 1.641]}>
        <mesh geometry={nodes.Cube156_1.geometry} material={materials['Material.022']} position={[0.003, 0.07, 0.001]} rotation={[-Math.PI, 0, 0]} scale={[0.175, 0.07, 0.167]} />
        <mesh geometry={nodes.LOGO001.geometry} material={materials['Material.016']} position={[0, -0.003, 0.001]} rotation={[-Math.PI, 0, 0]} scale={[0.139, 0.132, 0.139]} />
        <mesh geometry={nodes.Plane089.geometry} material={materials['SVGMat.025']} position={[0.004, -0.062, 0.001]} rotation={[-Math.PI, 0, 0]} scale={[0.219, 0.449, 0.215]} />
      </mesh>
      <mesh geometry={nodes.Cube157.geometry} material={materials.BOTTUNS} position={[-5.141, 4.41, -9.258]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.282, -0.03, -0.248]}>
        <mesh geometry={nodes.Cube158.geometry} material={materials['SVGMat.027']} position={[0.002, 1.014, 0]} scale={[0.957, 0.937, 0.937]} />
        <mesh geometry={nodes.Cube159_1.geometry} material={materials.BOTTUNS} position={[1.317, -0.627, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[-4.818, -0.087, -0.959]} />
      </mesh>
      <mesh geometry={nodes.sound_mixer.geometry} material={materials['FACE.PLATE.lo_res02.001_Bake1_baked']} position={[-9.695, 0.926, -8.616]} rotation={[-Math.PI / 2, 0, 1.574]} scale={[3.412, 3.059, 3.412]}>
        <mesh geometry={nodes.Cube160_1.geometry} material={materials.BOTTUNS} position={[0.008, 0.106, -0.007]} rotation={[-1.679, -1.568, 3.034]} scale={[0.073, 0.122, 0.257]} />
      </mesh>
      <mesh geometry={nodes.Cube162.geometry} material={materials.Wood} position={[-9.922, 1.824, -7.79]} scale={[0.084, 0.084, 0.106]}>
        <mesh geometry={nodes.flag_vietnam003.geometry} material={materials['vietnam.002']} position={[5.856, 6.323, 0.883]} rotation={[3.07, 0.475, 2.053]} scale={[2.199, 2.12, 2.893]} />
        <mesh geometry={nodes.Plane093.geometry} material={materials.Wood} position={[2.895, 5.524, 0.508]} rotation={[3.07, 0.475, 2.053]} scale={[3.21, 3.096, 4.224]} />
      </mesh>
      <mesh geometry={nodes.Cube161.geometry} material={materials.Wood} position={[-9.927, 1.824, -7.539]} scale={[0.084, 0.084, 0.106]}>
        <mesh geometry={nodes.flag_korea001.geometry} material={materials.korea} position={[5.827, 6.422, 0.762]} rotation={[3.085, 0.486, 1.978]} scale={[2.201, 2.116, 2.899]} />
        <mesh geometry={nodes.Plane091.geometry} material={materials.Wood} position={[2.925, 5.425, 0.395]} rotation={[3.085, 0.486, 1.978]} scale={[3.213, 3.089, 4.233]} />
      </mesh>
      <mesh geometry={nodes.Cube163.geometry} material={materials.Wood} position={[-10.166, 1.819, -7.614]} scale={[0.084, 0.084, 0.106]}>
        <mesh geometry={nodes.flag_korea.geometry} material={materials.korea} position={[0.76, 6.274, 4.373]} rotation={[-0.454, 1.483, -0.763]} scale={[2.156, 1.798, 3.454]} />
        <mesh geometry={nodes.flag_vietnam006.geometry} material={materials['vietnam.002']} position={[0.333, 6.618, -5.802]} rotation={[2.678, -0.878, 1.401]} scale={[2.16, 1.934, 3.263]} />
        <mesh geometry={nodes.Plane094_1.geometry} material={materials.Wood} position={[-0.015, 5.174, 2.278]} rotation={[-0.454, 1.483, -0.763]} scale={[3.148, 2.626, 5.043]} />
        <mesh geometry={nodes.Plane095.geometry} material={materials.Wood} position={[-0.198, 5.347, -3.607]} rotation={[2.678, -0.878, 1.401]} scale={[3.153, 2.824, 4.764]} />
      </mesh>
      <mesh geometry={nodes.Cube164.geometry} material={nodes.Cube164.material} position={[-10.006, 1.679, -7.684]} scale={[0.253, 0.04, 0.4]} />
      <mesh geometry={nodes.Cube165.geometry} material={materials.Wood} position={[-10.057, 1.698, -8.733]} scale={[0.282, 0.119, 0.6]} />
      <mesh geometry={nodes.Cube166.geometry} material={materials['SVGMat.023']} position={[-10.057, 1.88, -8.733]} scale={[0.196, 0.068, 0.279]} />
      <mesh geometry={nodes.Cube167.geometry} material={materials['SVGMat.023']} position={[-10.057, 2.005, -8.733]} rotation={[0, 0.366, 0]} scale={[0.191, 0.068, 0.292]} />
    </group>
  )
}

useGLTF.preload('/models/Phongtruyenthong.glb')
